#!/usr/bin/expect -f 

#使用 push_to_server ip username password ../release/release

if { $argc != 4 }  {
	send "echo push_to_server \[ip\] \[username\] \[password\] \[file\]\n"
	exit 1
}

set ip [lindex $argv 0]
set username [lindex $argv 1]
set password [lindex $argv 2]
set localFile [lindex $argv 3]

set timeout 600 
spawn scp -P 6208 ${localFile}  ${username}@${ip}:/home/caotao
expect {
	"*assword*" {send "${password}\r"}
	timeout  {
		#"scp fail\n"
		exit 1
	}
	
}

expect {
	"*100%*" {}
}

spawn ssh ${username}@${ip} -p 6208
expect {
	"*assword*" {send "${password}\r"}
}
expect {
	"*]$*" {
		send "ls -lh\r";
		send "echo \"unzip\"\r"
		interact;
	 }
}
